# Generated by Django 4.1.2 on 2022-11-02 18:15

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_ad']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
