# Generated by Django 4.1.2 on 2022-11-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_genre_category'),
        ('post', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genres', to='category.genre'),
        ),
    ]
