# Generated by Django 4.1.2 on 2022-11-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='director',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
