# Generated by Django 4.1.2 on 2022-11-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='director',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
