# Generated by Django 4.1.2 on 2022-11-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites_and_comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
