# Generated by Django 4.1.2 on 2022-11-03 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites_and_comments', '0002_alter_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='music',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='music',
            new_name='movie',
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('movie', 'owner')},
        ),
    ]
