# Generated by Django 4.1.2 on 2022-11-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('slug', models.SlugField(max_length=100)),
                ('title', models.SlugField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
