# Generated by Django 4.1.2 on 2022-11-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genre', to='category.category'),
        ),
    ]
